name: Deploy to Azure Web App

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'production'
        type: choice
        options:
        - production
        - staging

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore ./src/WebApi/WebApi.csproj

    - name: Build project
      run: dotnet build ./src/WebApi/WebApi.csproj --configuration Release --no-restore

    - name: Publish project
      run: dotnet publish ./src/WebApi/WebApi.csproj --configuration Release --output ./publish --no-build

    - name: Create deployment zip
      run: |
        cd publish
        zip -r ../publish.zip *

    - name: Login to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Web App
      run: |
        az webapp deploy --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --name ${{ secrets.AZURE_WEBAPP_NAME }} --src-path ./publish.zip --type zip
